version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: coordinadora_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coordinadora_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - coordinadora_db_data:/var/lib/mysql
    restart: always
  redis:
    image: redis:alpine
    container_name: coordinadora_redis
    ports:
      - '6379:6379'
    restart: always

  app:
    build: .
    container_name: coordinadora_app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    environment:
      PORT: 3000
      JWT_SECRET: ESunSesdsadasdcret@
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: coordinadora_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
    restart: always
volumes:
  coordinadora_db_data:
