version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: coordinadora_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coordinadora_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - coordinadora_db_data:/var/lib/mysql
volumes:
  coordinadora_db_data:
